spring:
  application:
    name: zwb-eureka
server:
  # eureka服务器端口号。尽管无论官网还是大部分参考书都使用8761，但默认并不是，而是8080
  port: 8761
  
eureka:
  server:
  ##Eureka Server端配置 直接干掉保护模式
  ##中小规模下，自我保护模式坑比好处多，所以关闭它
  ## enableSelfPreservation: false
  ##主动失效检测间隔,配置成5秒
    evictionIntervalTimerInMs: 5000
  ## 禁用readOnlyCacheMap
    useReadOnlyResponseCache: false
    
  #心跳阈值计算周期，如果开启自我保护模式，可以改一下这个配置
  #eureka.server.renewalThresholdUpdateIntervalMs: 120000
    renewal-percent-threshold: 0.29
    eviction-interval-timer-in-ms: 30000 

  instance:
    ## 心跳间隔，5秒
    leaseRenewalIntervalInSeconds: 5
    ## 没有心跳的淘汰时间，10秒
    leaseExpirationDurationInSeconds: 10
    #ip-address: 39.106.120.96
    #ip-address: 127.0.0.1
    #prefer-ip-address: true
    #hostname: zddream.cn
    hostname: localhost
  client:
    serviceUrl:
      #defaultZone: http://39.106.120.96:8761/eureka
      #defaultZone: http://${security.user.name}:${security.user.password}@10.13.22.18:${server.port}/eureka
      defaultZone:  http://${eureka.instance.hostname}:8762/eureka/
    registerWithEureka: true # eureka的高可用，需要互相注册，配置为true，覆盖本文件最上面的默认配置false。
    fetchRegistry: false # eureka之间如果网络不稳定，客户端一般也会缓存了注册列表，因此eureka服务可以不缓存，我觉得更能确保eureka之间的一致。